In [7]:
import requests
import pandas as pd 
import numpy as np 
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
import time 
import calendar

In [9]:
from datetime import datetime
now=datetime.now()
now.strftime("%Y-%m-%dT%H:%M:%S.%f")

'2026-03-25T13:59:21.651143'

In [249]:
data=[]
api_key='e62c395ec9844095ada4b688d012a975'
technical='time_series'
ticker='BTC/USD'
timezone='Asia/Calcutta'
interval='30min'
for yr in range(2022,2026):
    for m in range(1,5): 
        last_day=calendar.monthrange(yr,3*m)[1]   
        start_date=f'{yr}-{(3*m-2):02d}-01T00:00:00'
        end_date=f'{yr}-{(3*m):02d}-{last_day}T23:30:00'
        api_url=f'https://api.twelvedata.com/{technical}?symbol={ticker}&order=asc&timezone={timezone}&start_date={start_date}&end_date={end_date}&interval={interval}&outputsize=5000&apikey={api_key}'
        while True:
            session=requests.Session()
            retries=Retry(total=5,backoff_factor=1,status_forcelist=[429,500,502,503,504])
            session.mount("https://",HTTPAdapter(max_retries=retries))
            fetch=session.get(api_url).json()
            if "values" in fetch:
                df=pd.DataFrame(fetch['values'])
                data.append(df)
                time.sleep(8)
                break
            elif "code" in fetch and fetch["code"]==429:
                print("Rate limit exceeded")
                time.sleep(15)
            else: 
                print("API Error:",fetch)
                fetch=None
                break
data=pd.concat(data,ignore_index=True)
data['color']=np.where(data['close']>data['open'],1,0)
data['open']=pd.to_numeric(data['open'])
data['close']=pd.to_numeric(data['close'])
data['abs_body']=abs(data['close']-data['open'])
data['body']=(data['close']-data['open'])
data['high']=pd.to_numeric(data['high'])
data['low']=pd.to_numeric(data['low'])
data['upper_wick']=np.where(data['color']==1,data['high']-data['close'],data['high']-data['open'])
data['lower_wick']=np.where(data['color']==1,data['open']-data['low'],data['close']-data['low'])
data=data.dropna()
data=data.reset_index(drop=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
69992,2025-12-31 21:30:00,87830.030000,87932.17000,87558.00000,87792.55000,0,37.480000,-37.480000,102.140000,234.55000
69993,2025-12-31 22:00:00,87797.910000,87813.02000,87259.01000,87531.06000,0,266.850000,-266.850000,15.110000,272.05000
69994,2025-12-31 22:30:00,87531.060000,87637.99000,87356.29000,87496.24000,0,34.820000,-34.820000,106.930000,139.95000
69995,2025-12-31 23:00:00,87496.250000,87550.34000,87400.76000,87487.96000,0,8.290000,-8.290000,54.090000,87.20000
69996,2025-12-31 23:30:00,87487.960000,87866.97000,87433.01000,87814.33000,1,326.370000,326.370000,52.640000,54.95000

In [250]:
data['datetime']=pd.to_datetime(data['datetime'])
missing_times=pd.date_range(start="2022-01-01 00:00",end="2025-12-31 23:30",freq="30min").difference(data['datetime'])
missing_times

DatetimeIndex(['2022-02-19 19:30:00', '2022-02-19 20:00:00',
               '2022-02-19 20:30:00', '2022-02-19 21:00:00',
               '2022-02-19 21:30:00', '2022-02-19 22:00:00',
               '2022-02-19 22:30:00', '2022-02-19 23:00:00',
               '2022-02-19 23:30:00', '2022-02-20 00:00:00',
               ...
               '2025-10-25 21:30:00', '2025-10-25 22:00:00',
               '2025-10-25 22:30:00', '2025-10-25 23:00:00',
               '2025-10-25 23:30:00', '2025-10-26 00:00:00',
               '2025-10-26 00:30:00', '2025-10-26 01:00:00',
               '2025-10-26 01:30:00', '2025-10-26 02:00:00'],
              dtype='datetime64[ns]', length=131, freq=None)

In [6]:
missing_times=pd.date_range(start="2022-02-19 19:30",end="2022-02-20 02:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[40417.019531, 40382.390620, 40495.820310, 40316.121090, 39856.980470, 40183.230470, 39976.660160, 40073.031250, 40052.289060, 39966.011719, 40165.449220, 40245.160160, 40225.781250, 40079.878910, 39969.539060],
    "high":[40497.32812, 40449.48047, 40739.82031, 40316.12109, 40377.17188, 40382.75, 40360.03125, 40164.83984, 40052.28906, 40194.71875, 40268.60156, 40353.83984, 40294.37891, 40178.96094, 40149.51172],
    "low":[40316.82031, 39673.44922, 40278.39844, 39693.89844, 39464.60938, 40004.41016, 39976.66016, 39963.35156, 39825.62109, 39943.26172, 40084.64062, 40094.92969, 40050.39062, 39960.55859, 39916.57031],
    "close":[40354.148440, 40437.609380, 40278.398440, 39790.531250, 40153.898440, 40004.410160, 40095.351560, 40032.710940, 39983.800780, 40193.539060, 40268.601560, 40218.441410, 40123.281250, 39966.988280, 40128.75],
    "abs_body":[62.871091,55.21876,217.42187,525.58984,296.91797,178.82031,118.6914,40.32031,68.48828,227.527341,103.15234,26.71875,102.5,112.89063,159.21094],
    "body":[-62.871091,55.21876,-217.42187,-525.58984,296.91797,-178.82031,118.6914,-40.32031,-68.48828,227.527341,103.15234,-26.71875,-102.5,-112.89063,159.21094]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

NameError: name 'pd' is not defined

In [271]:
missing_times=pd.date_range(start="2022-04-03 02:00",end="2022-04-03 02:00",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[46324.46094],
    "high":[46391.42188],
    "low":[46111.011719],
    "close":[46164.92969],
    "abs_body":[159.53125],
    "body":[-159.53125]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.179690,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.000000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.550780,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.429690,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.949220,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70008,2022-02-20 01:00:00,40245.160160,40353.83984,40094.929690,40218.44141,NaN,26.718750,-26.718750,NaN,NaN
70009,2022-02-20 01:30:00,40225.781250,40294.37891,40050.390620,40123.28125,NaN,102.500000,-102.500000,NaN,NaN
70010,2022-02-20 02:00:00,40079.878910,40178.96094,39960.558590,39966.98828,NaN,112.890630,-112.890630,NaN,NaN
70011,2022-02-20 02:30:00,39969.539060,40149.51172,39916.570310,40128.75000,NaN,159.210940,159.210940,NaN,NaN
70012,2022-04-03 02:00:00,46324.460940,46391.42188,46111.011719,46164.92969,NaN,159.531250,-159.531250,NaN,NaN

In [272]:
missing_times=pd.date_range(start="2022-05-06 00:30",end="2022-05-06 01:00",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[39601.14844,39844.64062],
    "high":[39972.55078,39903.19922],
    "low":[39545.058594,39671.89844],
    "close":[39840.53906,39816.12109],
    "abs_body":[239.39062,28.51953],
    "body":[239.39062,-28.51953]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.179690,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.000000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.550780,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.429690,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.949220,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70010,2022-02-20 02:00:00,40079.878910,40178.96094,39960.558590,39966.98828,NaN,112.890630,-112.890630,NaN,NaN
70011,2022-02-20 02:30:00,39969.539060,40149.51172,39916.570310,40128.75000,NaN,159.210940,159.210940,NaN,NaN
70012,2022-04-03 02:00:00,46324.460940,46391.42188,46111.011719,46164.92969,NaN,159.531250,-159.531250,NaN,NaN
70013,2022-05-06 00:30:00,39601.148440,39972.55078,39545.058594,39840.53906,NaN,239.390620,239.390620,NaN,NaN
70014,2022-05-06 01:00:00,39844.640620,39903.19922,39671.898440,39816.12109,NaN,28.519530,-28.519530,NaN,NaN

In [273]:
missing_times=pd.date_range(start="2022-10-22 17:30",end="2022-10-22 18:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[18947.509770,18783.619140,18870.109380],
    "high":[18947.50977,18884.25,19004.060547],
    "low":[18679.75,18734.41016,18870.10938],
    "close":[18782.14062,18884.25,18962.26953],
    "abs_body":[165.369150,100.630860,92.16015],
    "body":[-165.369150,100.630860,92.160150]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.179690,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.000000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.550780,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.429690,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.949220,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70013,2022-05-06 00:30:00,39601.148440,39972.550780,39545.058594,39840.53906,NaN,239.390620,239.390620,NaN,NaN
70014,2022-05-06 01:00:00,39844.640620,39903.199220,39671.898440,39816.12109,NaN,28.519530,-28.519530,NaN,NaN
70015,2022-10-22 17:30:00,18947.509770,18947.509770,18679.750000,18782.14062,NaN,165.369150,-165.369150,NaN,NaN
70016,2022-10-22 18:00:00,18783.619140,18884.250000,18734.410160,18884.25000,NaN,100.630860,100.630860,NaN,NaN
70017,2022-10-22 18:30:00,18870.109380,19004.060547,18870.109380,18962.26953,NaN,92.160150,92.160150,NaN,NaN

In [274]:
missing_times=pd.date_range(start="2022-11-17 04:30",end="2022-11-17 05:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[16861.900390,16844.580080,16880.15039],
    "high":[16877.58984,16882.83008,16911.92969],
    "low":[16824.43945,16820.90039,16782.50977],
    "close":[16839.30078,16880.15039,16782.50977],
    "abs_body":[22.599610,35.570310,97.640620],
    "body":[-22.599610,35.570310,-97.640620]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.17969,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.00000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.55078,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.42969,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.94922,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70016,2022-10-22 18:00:00,18783.619140,18884.250000,18734.41016,18884.25000,NaN,100.630860,100.630860,NaN,NaN
70017,2022-10-22 18:30:00,18870.109380,19004.060547,18870.10938,18962.26953,NaN,92.160150,92.160150,NaN,NaN
70018,2022-11-17 04:30:00,16861.900390,16877.589840,16824.43945,16839.30078,NaN,22.599610,-22.599610,NaN,NaN
70019,2022-11-17 05:00:00,16844.580080,16882.830080,16820.90039,16880.15039,NaN,35.570310,35.570310,NaN,NaN
70020,2022-11-17 05:30:00,16880.150390,16911.929690,16782.50977,16782.50977,NaN,97.640620,-97.640620,NaN,NaN

In [275]:
missing_times=pd.date_range(start="2022-11-18 05:00",end="2022-11-18 10:00",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[16844.580080,16880.15039,16681.929690,16688.31055,16697.230470,16684.380860,16653.359380,16584.320310,16580.169920,16508.189450,16470.33008],
    "high":[16882.83008,16911.92969,16711.84961,16727.19922,16710.41992,16691.91016,16672.31055,16593.53906,16582.75977,16509.92969,16519.50977],
    "low":[16820.90039,16782.50977,16660.23047,16681.28906,16671.66992,16642.070312,16582.31055,16568.24023,16498.17969,16403.44922,16467.25],
    "close":[16880.15039,16782.50977,16688.230470,16697.349610,16680.490230,16655.009766,16582.310550,16583.050781,16502.509770,16472.599610,16489.439450],
    "abs_body":[35.570310,97.640620,6.30078,9.03906,16.74024,29.371094,71.04883,1.269529,77.660150,35.589840,19.109370],
    "body":[35.570310,-97.640620,6.300780,9.039060,-16.740240,-29.371094,-71.048830,-1.269529,-77.660150,-35.589840,19.109370]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.531250,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.871090,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.148440,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.410160,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.539060,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70027,2022-11-18 08:00:00,16653.359380,16672.31055,16582.31055,16582.310550,NaN,71.048830,-71.048830,NaN,NaN
70028,2022-11-18 08:30:00,16584.320310,16593.53906,16568.24023,16583.050781,NaN,1.269529,-1.269529,NaN,NaN
70029,2022-11-18 09:00:00,16580.169920,16582.75977,16498.17969,16502.509770,NaN,77.660150,-77.660150,NaN,NaN
70030,2022-11-18 09:30:00,16508.189450,16509.92969,16403.44922,16472.599610,NaN,35.589840,-35.589840,NaN,NaN
70031,2022-11-18 10:00:00,16470.330080,16519.50977,16467.25000,16489.439450,NaN,19.109370,19.109370,NaN,NaN

In [276]:
missing_times=pd.date_range(start="2022-11-19 05:00",end="2022-11-19 19:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[16844.58008,16880.15039,16681.92969,16688.31055,16697.23047,16684.38086,16653.35938,16584.32031,16580.16992,16508.18945,16470.33008,16825.42969,16810.34961,16791.14062,16744.73047,16778.31055,16767.76953,16727.86914,16711.51953,16715.65039,16727.16992,16730.38086,16781.96094,16750.039062,16736.25977,16737.16016,16754.5293,16759.91992,16777.41992,16742.2793],
    "high":[16882.83008,16911.92969,16711.84961,16727.19922,16710.41992,16691.91016,16672.31055,16593.53906,16582.75977,16509.92969,16519.50977,16825.42969,16815.41016,16806.4707,16788.050781,16785.25977,16770.11914,16731.35938,16721.9707,16740.089844,16745.68945,16789,16833.86914,16769.050781,16746.17969,16764.41992,16771.84961,16798.17969,16796.070312,16765.97070],
    "low":[16820.90039,16782.50977,16660.23047,16681.28906,16671.66992,16642.070312,16582.31055,16568.24023,16498.17969,16403.44922,16467.25,16806.82031,16772.98047,16744.21094,16743.75,16751.63086,16708.80078,16663.88086,16688.91016,16711.58984,16707.10938,16726.96094,16708.39062,16726.63086,16702.25977,16730.90039,16745.53906,16759.91992,16724.74023,16730.83008],
    "close":[16880.15039,16782.50977,16688.23047,16697.34961,16680.49023,16655.009766,16582.31055,16583.050781,16502.50977,16472.59961,16489.43945,16806.82031,16789.84961,16749.4707,16778.58984,16770.11914,16731.13086,16712.51953,16714.67969,16728.48047,16729.35938,16775.28906,16756.53906,16737.25,16737.83984,16753.91992,16764.2207,16777.070312,16744.66016,16759.94922],
    "abs_body":[35.57031,97.64062,6.30078,9.03906,16.74024,29.371094,71.04883,1.269529,77.66015,35.58984,19.10937,18.609380,20.5,41.66992,33.85937,8.19141,36.63867,15.34961,3.16016,12.83008,2.18946,44.9082,25.42188,12.789062,1.58007,16.75976,9.6914,17.150392,32.75976,17.66992],
    "body":[35.57031,-97.64062,6.30078,9.03906,-16.74024,-29.371094,-71.04883,-1.269529,-77.66015,-35.58984,19.10937,-18.609380,-20.5,-41.66992,33.85937,-8.19141,-36.63867,-15.34961,3.16016,12.83008,2.18946,44.9082,-25.42188,-12.789062,1.58007,16.75976,9.6914,17.150392,-32.75976,17.66992]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.17969,46640.531250,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.00000,46080.871090,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.55078,45693.148440,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.42969,46037.410160,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.94922,45881.539060,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70057,2022-11-19 17:30:00,16737.160160,16764.419920,16730.90039,16753.919920,NaN,16.759760,16.759760,NaN,NaN
70058,2022-11-19 18:00:00,16754.529300,16771.849610,16745.53906,16764.220700,NaN,9.691400,9.691400,NaN,NaN
70059,2022-11-19 18:30:00,16759.919920,16798.179690,16759.91992,16777.070312,NaN,17.150392,17.150392,NaN,NaN
70060,2022-11-19 19:00:00,16777.419920,16796.070312,16724.74023,16744.660160,NaN,32.759760,-32.759760,NaN,NaN
70061,2022-11-19 19:30:00,16742.279300,16765.970700,16730.83008,16759.949220,NaN,17.669920,17.669920,NaN,NaN

In [277]:
missing_times=pd.date_range(start="2022-11-20 14:30",end="2022-11-20 15:00",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[16715.65039,16727.16992],
    "high":[16740.089844,16745.68945],
    "low":[16711.58984,16707.10938],
    "close":[16728.48047,16729.35938],
    "abs_body":[12.83008,2.18946],
    "body":[12.83008,2.18946]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.17969,46640.531250,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.00000,46080.871090,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.55078,45693.148440,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.42969,46037.410160,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.94922,45881.539060,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70059,2022-11-19 18:30:00,16759.919920,16798.179690,16759.91992,16777.070312,NaN,17.150392,17.150392,NaN,NaN
70060,2022-11-19 19:00:00,16777.419920,16796.070312,16724.74023,16744.660160,NaN,32.759760,-32.759760,NaN,NaN
70061,2022-11-19 19:30:00,16742.279300,16765.970700,16730.83008,16759.949220,NaN,17.669920,17.669920,NaN,NaN
70062,2022-11-20 14:30:00,16715.650390,16740.089844,16711.58984,16728.480470,NaN,12.830080,12.830080,NaN,NaN
70063,2022-11-20 15:00:00,16727.169920,16745.689450,16707.10938,16729.359380,NaN,2.189460,2.189460,NaN,NaN

In [278]:
missing_times=pd.date_range(start="2022-11-20 16:00",end="2022-11-20 16:00",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[16730.38086],
    "high":[16789],
    "low":[16726.96094],
    "close":[16775.28906],
    "abs_body":[44.9082],
    "body":[44.9082]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.17969,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.00000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.55078,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.42969,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.94922,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70060,2022-11-19 19:00:00,16777.419920,16796.070312,16724.74023,16744.66016,NaN,32.759760,-32.759760,NaN,NaN
70061,2022-11-19 19:30:00,16742.279300,16765.970700,16730.83008,16759.94922,NaN,17.669920,17.669920,NaN,NaN
70062,2022-11-20 14:30:00,16715.650390,16740.089844,16711.58984,16728.48047,NaN,12.830080,12.830080,NaN,NaN
70063,2022-11-20 15:00:00,16727.169920,16745.689450,16707.10938,16729.35938,NaN,2.189460,2.189460,NaN,NaN
70064,2022-11-20 16:00:00,16730.380860,16789.000000,16726.96094,16775.28906,NaN,44.908200,44.908200,NaN,NaN

In [279]:
missing_times=pd.date_range(start="2022-12-03 13:00",end="2022-12-03 16:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[16932.40039,16958.76953,16948.029297,16967.91016,16965.92969,16967.32031,16954.35938,16967.060547],
    "high":[16970.65039,16965.75977,16972.85938,16978.36914,16988.4707,16977.070312,16968.7207,16995.019531],
    "low":[16932.40039,16941.59961,16948.029297,16960.82031,16964.58984,16952.78906,16951.17969,16959.36914],
    "close":[16965.30078,16947.4707,16966.25977,16966.46094,16966.029297,16954.82031,16966.88086,16974.080078],
    "abs_body":[32.90039,11.29883,18.230473,1.44922,0.099607,12.5,12.52148,7.019531],
    "body":[32.90039,-11.29883,-18.230473,-1.44922,0.099607,-12.5,12.52148,7.019531]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.17969,46640.531250,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.00000,46080.871090,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.55078,45693.148440,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.42969,46037.410160,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.94922,45881.539060,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70068,2022-12-03 14:30:00,16967.910160,16978.369140,16960.82031,16966.460940,NaN,1.449220,-1.449220,NaN,NaN
70069,2022-12-03 15:00:00,16965.929690,16988.470700,16964.58984,16966.029297,NaN,0.099607,0.099607,NaN,NaN
70070,2022-12-03 15:30:00,16967.320310,16977.070312,16952.78906,16954.820310,NaN,12.500000,-12.500000,NaN,NaN
70071,2022-12-03 16:00:00,16954.359380,16968.720700,16951.17969,16966.880860,NaN,12.521480,12.521480,NaN,NaN
70072,2022-12-03 16:30:00,16967.060547,16995.019531,16959.36914,16974.080078,NaN,7.019531,7.019531,NaN,NaN

In [ ]:
missing_times=pd.date_range(start="2023-02-22 21:30",end="2023-02-23 11:30",freq="30min")
missing_df=pd.DataFrame({ 
    "datetime":missing_times,
    "open":[24563.85938,24381.33984,24409.80078,24401.59961,24641.91016,24629.23047,24689.48047,24640.019531,24607.7207,24449.66992,24459.94922,24241.070312,24190.16992,24295.82031,24389,24361.81055,24452.98047,24412.73047,24403.23047,24360.14062,24203.83984,24036.24023,24172.31055,24229.11914,24201.96094,24163.82031,24158.83984,24026.33008,24102.78906],
    "high":[24587.75977,24444.42969,24444.65039,24652.85938,24746.90039,24732.019531,24693.90039,24686.53906,24642.88086,24525.67969,24536.65039,24332.26953,24316.30078,24428.84961,24404.33984,24451.90039,24474.51953,24425.5293,24432.75,24392.070312,24203.83984,24195.30078,24270.40039,24247.11914,24222.73047,24170.32031,24168.15039,24113.029297,24128.25977],
    "low":[24321.32031,24301.5293,24380.76953,24401.59961,24589.96094,24569.58008,24564.4707,24558.17969,24450.56055,24434.57031,24159.85938,24173.41016,24174.28906,24280.82031,24341.019531,24351.32031,24411.49023,24276.41016,24356.019531,24156.5,23969.66016,23873.0097656,24133.11914,24155.86914,24160.029297,24031.099609,24007.91992,24013.31055,24028.17969],
    "close":[24377.19922,24403.060547,24412.69922,24652.85938,24631.66016,24693.90039,24636.63086,24595.96094,24450.88086,24464.41016,24257.78906,24175.57031,24295.33984,24384.94922,24356.9707,24451.90039,24411.83984,24402.7793,24365.51953,24195.76953,24036.60938,24169.50977,24238.68945,24200.099609,24162.17969,24161.21094,24032.81055,24107.34961,24044.48047],
    "abs_body":[186.66016,21.720707,2.89844,251.25977,10.25,64.66992,52.84961,44.058591,156.83984,14.74024,202.16016,65.500002,105.16992,89.12891,32.0293,90.08984,41.14063,9.95117,37.71094,164.37109,167.23046,133.26954,66.3789,29.019531,39.78125,2.60937,126.02929,81.01953,58.30859],
    "body":[-186.66016,21.720707,2.89844,251.25977,-10.25,64.66992,-52.84961,-44.058591,-156.83984,14.74024,-202.16016,-65.500002,105.16992,89.12891,-32.0293,90.08984,-41.14063,-9.95117,-37.71094,-164.37109,-167.23046,133.26954,66.3789,-29.019531,-39.78125,-2.60937,-126.02929,81.01953,-58.30859]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.179690,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.000000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.550780,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.429690,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.949220,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70097,2023-02-23 09:30:00,24201.960940,24222.730470,24160.029297,24162.17969,NaN,39.781250,-39.781250,NaN,NaN
70098,2023-02-23 10:00:00,24163.820310,24170.320310,24031.099609,24161.21094,NaN,2.609370,-2.609370,NaN,NaN
70099,2023-02-23 10:30:00,24158.839840,24168.150390,24007.919920,24032.81055,NaN,126.029290,-126.029290,NaN,NaN
70100,2023-02-23 11:00:00,24026.330080,24113.029297,24013.310550,24107.34961,NaN,81.019530,81.019530,NaN,NaN
70101,2023-02-23 11:30:00,24102.789060,24128.259770,24028.179690,24044.48047,NaN,58.308590,-58.308590,NaN,NaN

In [281]:
missing_times=pd.date_range(start="2023-03-04 23:00",end="2023-03-05 01:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[22422.019531,22420.60938,22386.86914,22314.14062,22306.85938,22354.26953],
    "high":[22448.36914,22422.050781,22394.24023,22355.99023,22389.84961,22377.71094],
    "low":[22395.92969,22375.25,22263.57031,22294.13086,22301.080078,22333.2207],
    "close":[22417.42969,22394.24023,22316.21094,22311.89062,22356.48047,22355.060547],
    "abs_body":[4.589841,26.36915,70.6582,2.25,49.62109,0.791017],
    "body":[-4.589841,-26.36915,-70.6582,-2.25,49.62109,0.791017]
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.179690,46640.531250,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.000000,46080.871090,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.550780,45693.148440,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.429690,46037.410160,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.949220,45881.539060,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70103,2023-03-04 23:30:00,22420.609380,22422.050781,22375.250000,22394.240230,NaN,26.369150,-26.369150,NaN,NaN
70104,2023-03-05 00:00:00,22386.869140,22394.240230,22263.570310,22316.210940,NaN,70.658200,-70.658200,NaN,NaN
70105,2023-03-05 00:30:00,22314.140620,22355.990230,22294.130860,22311.890620,NaN,2.250000,-2.250000,NaN,NaN
70106,2023-03-05 01:00:00,22306.859380,22389.849610,22301.080078,22356.480470,NaN,49.621090,49.621090,NaN,NaN
70107,2023-03-05 01:30:00,22354.269530,22377.710940,22333.220700,22355.060547,NaN,0.791017,0.791017,NaN,NaN

In [282]:
missing_times=pd.date_range(start="2023-07-20 00:00",end="2023-07-20 03:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[29929.14,29909.63,29775.01,29720.64,29728.11,29783.77,29830.69,29807.85],
    "high":[29932.4,29946.23,29817.33,29794.65,29818.44,29841.05,29831.53,29823.14],
    "low":[29859.69,29771.55,29685.27,29704.95,29690.39,29756.01,29778.89,29768.22],
    "close":[29910.96,29775,29722.14,29728.11,29783.61,29830.7,29807.88,29790.82],
    "abs_body":[18.18,134.63,52.87,7.47,55.5,46.93,22.81,17.03],
    "body":[-18.18,-134.63,-52.87,7.47,55.5,46.93,-22.81,-17.03]
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70111,2023-07-20 01:30:00,29720.640000,29794.65000,29704.95000,29728.11000,NaN,7.470000,7.470000,NaN,NaN
70112,2023-07-20 02:00:00,29728.110000,29818.44000,29690.39000,29783.61000,NaN,55.500000,55.500000,NaN,NaN
70113,2023-07-20 02:30:00,29783.770000,29841.05000,29756.01000,29830.70000,NaN,46.930000,46.930000,NaN,NaN
70114,2023-07-20 03:00:00,29830.690000,29831.53000,29778.89000,29807.88000,NaN,22.810000,-22.810000,NaN,NaN
70115,2023-07-20 03:30:00,29807.850000,29823.14000,29768.22000,29790.82000,NaN,17.030000,-17.030000,NaN,NaN

In [283]:
missing_times=pd.date_range(start="2024-10-26 22:00",end="2024-10-26 22:00",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[67579.54],
    "high":[67864.16],
    "low":[67512.9],
    "close":[67633.74],
    "abs_body":[54.2],
    "body":[54.2]
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70112,2023-07-20 02:00:00,29728.110000,29818.44000,29690.39000,29783.61000,NaN,55.500000,55.500000,NaN,NaN
70113,2023-07-20 02:30:00,29783.770000,29841.05000,29756.01000,29830.70000,NaN,46.930000,46.930000,NaN,NaN
70114,2023-07-20 03:00:00,29830.690000,29831.53000,29778.89000,29807.88000,NaN,22.810000,-22.810000,NaN,NaN
70115,2023-07-20 03:30:00,29807.850000,29823.14000,29768.22000,29790.82000,NaN,17.030000,-17.030000,NaN,NaN
70116,2024-10-26 22:00:00,67579.540000,67864.16000,67512.90000,67633.74000,NaN,54.200000,54.200000,NaN,NaN

In [284]:
missing_times=pd.date_range(start="2025-10-25 21:00",end="2025-10-26 02:00",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[110608.48,110070.08,110370.87,110282.04,110516.01,110231.46,110528.01,110621.56,110948.65,110624.01,110754],
    "high":[110636.73,110411.24,110378.96,110600,110519.16,110658.51,110654.51,110980.7,110955.64,110817.37,111040.55],
    "low":[109910.01,109804.93,109930,110195.8,110231.47,110165.84,110422,110617.05,110506.46,110485.4,110676.22],
    "close":[110070.09,110374.01,110286.93,110516.01,110233.73,110524.36,110621.56,110948.65,110624.14,110753.99,110920.22],
    "abs_body":[538.39,303.93,83.94,233.97,282.28,292.9,93.55,327.09,324.51,129.98,166.22],
    "body":[-538.39,303.93,-83.94,233.97,-282.28,292.9,93.55,327.09,-324.51,129.98,166.22]
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70123,2025-10-26 00:00:00,110528.010000,110654.51000,110422.00000,110621.56000,NaN,93.550000,93.550000,NaN,NaN
70124,2025-10-26 00:30:00,110621.560000,110980.70000,110617.05000,110948.65000,NaN,327.090000,327.090000,NaN,NaN
70125,2025-10-26 01:00:00,110948.650000,110955.64000,110506.46000,110624.14000,NaN,324.510000,-324.510000,NaN,NaN
70126,2025-10-26 01:30:00,110624.010000,110817.37000,110485.40000,110753.99000,NaN,129.980000,129.980000,NaN,NaN
70127,2025-10-26 02:00:00,110754.000000,111040.55000,110676.22000,110920.22000,NaN,166.220000,166.220000,NaN,NaN

In [285]:
data['datetime']=pd.to_datetime(data['datetime'])
data=data.sort_values("datetime").reset_index(drop=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70123,2025-12-31 21:30:00,87830.030000,87932.17000,87558.00000,87792.55000,0.0,37.480000,-37.480000,102.140000,234.55000
70124,2025-12-31 22:00:00,87797.910000,87813.02000,87259.01000,87531.06000,0.0,266.850000,-266.850000,15.110000,272.05000
70125,2025-12-31 22:30:00,87531.060000,87637.99000,87356.29000,87496.24000,0.0,34.820000,-34.820000,106.930000,139.95000
70126,2025-12-31 23:00:00,87496.250000,87550.34000,87400.76000,87487.96000,0.0,8.290000,-8.290000,54.090000,87.20000
70127,2025-12-31 23:30:00,87487.960000,87866.97000,87433.01000,87814.33000,1.0,326.370000,326.370000,52.640000,54.95000

In [8]:
df_volume=[]
df_takervolume=[]
df_opentime=[]
df_trades=[]
interval='30m'
for yr in range(2022,2026):
    for m in range(1,13): 
        start_date=f'{yr}-{(m):02d}-01'
        end_date=f'{yr}-{(m):02d}-16'
        start_ms=int(time.mktime(time.strptime(start_date,"%Y-%m-%d")))*1000
        end_ms=int(time.mktime(time.strptime(end_date,"%Y-%m-%d")))*1000
        api_url=f"https://api1.binance.com/api/v3/klines?symbol=BTCUSDT&interval={interval}&startTime={start_ms}&endTime={end_ms}&limit=1000"
        while True:
            session=requests.Session()
            retries=Retry(total=5,backoff_factor=1,status_forcelist=[429,500,502,503,504])
            session.mount("https://",HTTPAdapter(max_retries=retries))
            fetch=session.get(api_url).json()
            if fetch:
                open_time=[value[0] for value in fetch]
                volume=[float(value[7]) for value in fetch]
                taker_volume=[float(value[10]) for value in fetch]
                trades=[float(value[8]) for value in fetch]
                df_volume.extend(volume)
                df_opentime.extend(open_time) 
                df_takervolume.extend(taker_volume)
                df_trades.extend(trades)
                time.sleep(4)
                break
            else: 
                print("API Error:",fetch)
                fetch=None
                break
        last_day=calendar.monthrange(yr,m)[1]
        start_date=f'{yr}-{(m):02d}-16'
        end_date=f'{yr}-{(m):02d}-{(last_day)}'
        start_ms=int(time.mktime(time.strptime(start_date,"%Y-%m-%d")))*1000
        end_ms=int(time.mktime(time.strptime(end_date,"%Y-%m-%d")))*1000
        api_url=f"https://api1.binance.com/api/v3/klines?symbol=BTCUSDT&interval={interval}&startTime={start_ms}&endTime={end_ms}&limit=1000"
        while True:
            session=requests.Session()
            retries=Retry(total=5,backoff_factor=1,status_forcelist=[429,500,502,503,504])
            session.mount("https://",HTTPAdapter(max_retries=retries))
            fetch=session.get(api_url).json()
            if fetch:
                open_time=[value[0] for value in fetch]
                volume=[float(value[7]) for value in fetch]
                taker_volume=[float(value[10]) for value in fetch]
                trades=[float(value[8]) for value in fetch]
                df_volume.extend(volume)
                df_opentime.extend(open_time) 
                df_takervolume.extend(taker_volume)
                df_trades.extend(trades)
                time.sleep(4)
                break
            else: 
                print("API Error:",fetch)
                fetch=None
                break
df=pd.DataFrame({
    'open_time':pd.to_datetime(df_opentime,unit='ms'),
    'volume':df_volume,
    'taker_volume':df_takervolume,
    'no_of_trades':df_trades
}).dropna()
df['open_time']=df['open_time'].dt.tz_localize('UTC').dt.tz_convert('Asia/Kolkata')
df

                      open_time        volume  taker_volume  no_of_trades
0     2022-01-01 01:00:00+05:30  1.146748e+08  4.930189e+07       49761.0
1     2022-01-01 01:30:00+05:30  6.113717e+07  3.375046e+07       32543.0
2     2022-01-01 02:00:00+05:30  2.308425e+07  1.213224e+07       18757.0
3     2022-01-01 02:30:00+05:30  4.087805e+07  2.338065e+07       27016.0
4     2022-01-01 03:00:00+05:30  3.909260e+07  2.144366e+07       27563.0
...                         ...           ...           ...           ...
67913 2025-12-30 23:00:00+05:30  4.250846e+07  2.167012e+07      105824.0
67914 2025-12-30 23:30:00+05:30  1.873078e+07  1.009447e+07       72103.0
67915 2025-12-31 00:00:00+05:30  1.963927e+07  9.808946e+06       63776.0
67916 2025-12-31 00:30:00+05:30  2.163632e+07  1.154721e+07       93779.0
67917 2025-12-31 01:00:00+05:30  8.827184e+06  3.978945e+06       52946.0

[67918 rows x 4 columns]

In [9]:
df.to_csv('binance_22-25.csv',index=False)

In [3]:
import time
time.time()

1774947119.4192133

In [5]:
import requests
def get_binance_server_time():  
    response=requests.get("https://api1.binance.com/api/v3/time")
    return response.json()['serverTime']
get_binance_server_time()

1774943942379

In [ ]:
merged_data=pd.merge_asof(data,df,left_index=True,right_index=True,direction='nearest',tolerance=60)
merged_data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick,open_time,volume,taker_volume,no_of_trades
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0,253.769530,-253.769530,57.468750,83.35156,2021-12-31 18:30:00,5.741317e+07,2.218630e+07,33022.0
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0,575.390630,-575.390630,0.000000,5.87109,2021-12-31 19:00:00,6.294230e+07,2.873560e+07,37711.0
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0,370.921872,-370.921872,254.800778,36.59766,2021-12-31 19:30:00,1.146748e+08,4.930189e+07,49761.0
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1,365.679690,365.679690,158.398430,16.30078,2021-12-31 20:00:00,6.113717e+07,3.375046e+07,32543.0
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0,160.480471,-160.480471,73.191409,57.58984,2021-12-31 20:30:00,2.308425e+07,1.213224e+07,18757.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69240,2025-12-30 22:00:00,89136.030000,89190.74000,88484.70000,88659.99000,0,476.040000,-476.040000,54.710000,175.29000,NaT,NaN,NaN,NaN
69241,2025-12-30 22:30:00,88660.000000,88839.49000,88414.06000,88549.49000,0,110.510000,-110.510000,179.490000,135.43000,NaT,NaN,NaN,NaN
69242,2025-12-30 23:00:00,88546.190000,88613.98000,88050.17000,88297.59000,0,248.600000,-248.600000,67.790000,247.42000,NaT,NaN,NaN,NaN
69243,2025-12-30 23:30:00,88297.580000,88386.68000,88203.77000,88304.86000,1,7.280000,7.280000,81.820000,93.81000,NaT,NaN,NaN,NaN
69244,2025-12-31 00:00:00,88304.860000,88447.00000,88051.80000,88226.50000,0,78.360000,-78.360000,142.140000,174.70000,NaT,NaN,NaN,NaN

In [ ]:
merged_data['volume']=pd.to_numeric(merged_data['volume'])
merged_data['taker_volume']=pd.to_numeric(merged_data['taker_volume'])
merged_data['no_of_trades']=pd.to_numeric(merged_data['no_of_trades'])
merged_data['taker_buy_ratio']=merged_data['taker_volume']/merged_data['volume']
merged_data['avg_trade_size']=merged_data['volume']/merged_data['no_of_trades']
merged_data['vol_z']=(merged_data['volume']-merged_data['volume'].rolling(48).mean().shift(1))/merged_data['volume'].rolling(48).std().shift(1)

In [ ]:
data=merged_data
data

NameError: name 'merged_data' is not defined

In [251]:
pfvg=0
nfvg=0
for i in range(1,len(data)-1):
    if data['low'][i+1]-data['high'][i-1]>25:
        pfvg+=1
    elif data['low'][i-1]-data['high'][i+1]>25:
        nfvg+=1
pfvg,nfvg

(4776, 4390)

In [452]:
fvgs=[25,50,75,100,150,200,250,300,350]
fvgs=[0.001,0.002,0.003,0.004,0.006,0.008,0.01,0.012,0.014]
horizons=[4,6,8,10,12,14,16,18,20,22,24,26,28]
for f in fvgs:
    for h in horizons:
        pfvg_ret=nfvg_ret=pfvg=nfvg=pret_per=nret_per=0
        for i in range(1,len(data)-h):
            if (data['low'][i+1]-data['high'][i-1])/data['close'][i]>f:
                pfvg_ret+=data['close'][i+h]-data['close'][i]
                pfvg+=1
                pret_per+=(data['close'][i+h]-data['close'][i])/data['close'][i]
            elif (data['low'][i-1]-data['high'][i+1])/data['close'][i]>f:
                nfvg_ret+=data['close'][i]-data['close'][i+h]
                nfvg+=1
                nret_per+=(data['close'][i]-data['close'][i+h])/data['close'][i]
        print(f'fair value gap {f}; horizon {h}: ',pfvg_ret/pfvg,nfvg_ret/nfvg,pret_per*100/pfvg,nret_per*100/nfvg,pfvg,nfvg)

fair value gap 0.001; horizon 4:  116.93878762432 113.85695868337164 0.2228462146341747 0.1981778077870691 3676 3464
fair value gap 0.001; horizon 6:  120.71049589162101 114.42150379601591 0.23678358934191276 0.19380607073933848 3676 3464
fair value gap 0.001; horizon 8:  123.46664056158893 112.12187475644123 0.24166608773334214 0.1903300617194902 3676 3462
fair value gap 0.001; horizon 10:  119.6066200321548 114.38781360346609 0.2299538530186649 0.1884196523005446 3676 3462
fair value gap 0.001; horizon 12:  116.70699467328598 115.095160696476 0.2352324274946461 0.1929776137118516 3676 3462
fair value gap 0.001; horizon 14:  115.33141911828059 113.5795224079142 0.23654063640412246 0.1853639700315795 3676 3462
fair value gap 0.001; horizon 16:  124.3375604186344 113.68288857654535 0.25495720593780863 0.1863715719259863 3676 3462
fair value gap 0.001; horizon 18:  135.94189025952122 110.07587507365696 0.27787808686420395 0.1805160130210455 3676 3462
fair value gap 0.001; horizon 20:  126.32669875416174 111.98553120023128 0.2629830377298089 0.19108505601915718 3676 3462
fair value gap 0.001; horizon 22:  130.8629753713818 115.29297634251878 0.26940413900342913 0.19888291474393735 3676 3462
fair value gap 0.001; horizon 24:  135.65439938079416 122.62476903951479 0.28209674083535363 0.204310879311302 3676 3462
fair value gap 0.001; horizon 26:  135.00051481828066 116.34895019956645 0.2878884601070721 0.19793931715355786 3676 3462
fair value gap 0.001; horizon 28:  143.5638522583789 107.7148870088968 0.2995488948922997 0.18668105765826135 3676 3462
fair value gap 0.002; horizon 4:  144.73817872837452 129.9107321449626 0.2841739072002278 0.24034597524582058 2178 2144
fair value gap 0.002; horizon 6:  143.25274242369156 137.60062954972028 0.2897748380931674 0.25003119846031946 2178 2144
fair value gap 0.002; horizon 8:  139.235042703765 129.26595291777883 0.28776557321193247 0.23491529418742108 2178 2143
fair value gap 0.002; horizon 10:  136.28333379164386 128.35207424218362 0.2729303551156854 0.22969035397536303 2178 2143
fair value gap 0.002; horizon 12:  127.95616775151524 123.64013718282784 0.2736457553681389 0.22898959754047787 2178 2143
fair value gap 0.002; horizon 14:  129.725101222957 122.59492184824975 0.28171465537918516 0.22837918067529342 2178 2143
fair value gap 0.002; horizon 16:  138.47315117621707 112.66732385431642 0.29528196443958843 0.21770575150408208 2178 2143
fair value gap 0.002; horizon 18:  155.17764958255307 108.53421879906676 0.32773021682626396 0.20178004654944132 2178 2143
fair value gap 0.002; horizon 20:  144.23920265114776 117.42500351031299 0.30740956771167866 0.2151712296138604 2178 2143
fair value gap 0.002; horizon 22:  149.07520714031216 121.79979322389177 0.31457331982794834 0.23700392410063825 2178 2143
fair value gap 0.002; horizon 24:  155.3181822896235 124.04721319430699 0.33315854976293224 0.2389132073883221 2178 2143
fair value gap 0.002; horizon 26:  157.70366089338847 124.24211518390094 0.3514770000607888 0.24146260608190143 2178 2143
fair value gap 0.002; horizon 28:  161.5693496616166 110.66880489640677 0.35921956048775233 0.22831938727994178 2178 2143
fair value gap 0.003; horizon 4:  165.23113299314227 141.01770144071665 0.3274923454771337 0.2679053484822953 1429 1395
fair value gap 0.003; horizon 6:  159.51106509909047 153.62886631770616 0.319466153853576 0.27730721429440447 1429 1395
fair value gap 0.003; horizon 8:  171.4154080624216 145.50870428565278 0.3374250328949387 0.25892272931817145 1429 1394
fair value gap 0.003; horizon 10:  168.98388396151176 142.99950833242445 0.31614970061916203 0.25183004933755004 1429 1394
fair value gap 0.003; horizon 12:  158.43329982687226 149.92885828622667 0.3140725553394513 0.2672724052615222 1429 1394
fair value gap 0.003; horizon 14:  157.56596281973398 142.1796377394544 0.32480361865012464 0.26149637693584005 1429 1394
fair value gap 0.003; horizon 16:  171.0726960258927 131.81475053816345 0.34089798559552237 0.25404892984839905 1429 1394
fair value gap 0.003; horizon 18:  194.51156386312115 126.5912841898136 0.39106151638745973 0.23006945451293617 1429 1394
fair value gap 0.003; horizon 20:  184.57780435297406 147.25980103916766 0.3661834143700019 0.2652868781460011 1429 1394
fair value gap 0.003; horizon 22:  186.88816260601854 145.30226733902444 0.36705350840982365 0.2740581450352825 1429 1394
fair value gap 0.003; horizon 24:  194.74333842743198 151.31668759096107 0.39328533173976027 0.28539439806470324 1429 1394
fair value gap 0.003; horizon 26:  194.9815002135758 155.55613116578164 0.4078462973395349 0.29226045244390025 1429 1394
fair value gap 0.003; horizon 28:  204.5104536971311 134.34584371492107 0.425196473492538 0.2696717609113289 1429 1394
fair value gap 0.004; horizon 4:  175.07373192379086 147.885312940535 0.35014447696597206 0.2875201469697369 1013 1009
fair value gap 0.004; horizon 6:  170.0336002540967 151.05066824023788 0.3387822384324092 0.2820472526463383 1013 1009
fair value gap 0.004; horizon 8:  180.1459562071077 131.66112069166653 0.34780967803711754 0.25355303474232527 1013 1008
fair value gap 0.004; horizon 10:  183.23765669733484 135.4646972236111 0.32979512499667707 0.2549064389066346 1013 1008
fair value gap 0.004; horizon 12:  180.52194373129362 149.87997939186513 0.34385663823449236 0.29485717994916055 1013 1008
fair value gap 0.004; horizon 14:  191.2845827032578 141.46998993134898 0.37812482802655795 0.28349784277994955 1013 1008
fair value gap 0.004; horizon 16:  209.1172740114514 131.08186024821418 0.4037150349294141 0.2739502282766795 1013 1008
fair value gap 0.004; horizon 18:  225.72512988785815 127.20660079523803 0.45065467873937987 0.24566750135959312 1013 1008
fair value gap 0.004; horizon 20:  220.95815650266528 151.8185121464284 0.44113482045782804 0.2868543216825289 1013 1008
fair value gap 0.004; horizon 22:  236.23954163534086 154.46983966488088 0.4710769873432104 0.3107924605568626 1013 1008
fair value gap 0.004; horizon 24:  249.5466036874632 158.86547127757927 0.5116360557332303 0.3170009985056109 1013 1008
fair value gap 0.004; horizon 26:  255.09200591451145 164.14181457708327 0.537143793513509 0.3261007436921636 1013 1008
fair value gap 0.004; horizon 28:  266.0439722345505 141.9675578835315 0.5577219240678356 0.3026659011138234 1013 1008
fair value gap 0.006; horizon 4:  191.72473938544192 146.73988613811173 0.40938635021704184 0.31191550060384515 577 572
fair value gap 0.006; horizon 6:  189.90942590537256 155.90041974580416 0.40880200343636447 0.30569933768975105 577 572
fair value gap 0.006; horizon 8:  202.24052168353546 136.07744325594408 0.41072306482934545 0.2508000670520486 577 572
fair value gap 0.006; horizon 10:  196.47471719653393 129.20457057237746 0.38449213916594693 0.23028889227412155 577 572
fair value gap 0.006; horizon 12:  199.9514114450608 151.62854416468545 0.40669608567307347 0.2726559613481685 577 572
fair value gap 0.006; horizon 14:  201.69691861663782 143.59221769020988 0.41407997035907995 0.27611845183578604 577 572
fair value gap 0.006; horizon 16:  212.3722403036397 130.21879360314682 0.43094710067071107 0.24535066755551174 577 572
fair value gap 0.006; horizon 18:  233.50509180485264 108.13266726398604 0.5003567981650207 0.1822590090359038 577 572
fair value gap 0.006; horizon 20:  217.68865528110933 136.70400696853156 0.4660383064371298 0.24368302454184765 577 572
fair value gap 0.006; horizon 22:  238.1226430062393 130.68533011748264 0.5206816167070947 0.25423250351029497 577 572
fair value gap 0.006; horizon 24:  253.92775755285993 124.06282607832175 0.5723802616406373 0.23046439889224207 577 572
fair value gap 0.006; horizon 26:  274.7456029528596 113.6646114038462 0.6402960779599811 0.22045964478238705 577 572
fair value gap 0.006; horizon 28:  282.8704348461005 91.97188187237752 0.6485029306945653 0.20975700578088827 577 572
fair value gap 0.008; horizon 4:  187.35586857507272 172.1238550498581 0.3957000347410394 0.37619118692125914 345 353
fair value gap 0.008; horizon 6:  194.4726555895653 197.45089888838524 0.4094680859482649 0.40410564530235565 345 353
fair value gap 0.008; horizon 8:  200.2783730823188 188.72442956657207 0.37812543127248754 0.342355002956961 345 353
fair value gap 0.008; horizon 10:  215.55182130376832 179.22653345495743 0.35482940333280205 0.2848295350292733 345 353
fair value gap 0.008; horizon 12:  212.01264390782643 208.23999258413608 0.3519307444525177 0.3857821930401048 345 353
fair value gap 0.008; horizon 14:  216.49218300231897 200.3100287138812 0.34946809576050936 0.3866306467994762 345 353
fair value gap 0.008; horizon 16:  239.66202959942046 170.80090826458908 0.4135550246432044 0.32583670443194285 345 353
fair value gap 0.008; horizon 18:  258.59829344927545 170.275391686119 0.4693640572575603 0.311426456392831 345 353
fair value gap 0.008; horizon 20:  225.03755505449274 177.23125280169992 0.38699759089376157 0.33846493747601863 345 353
fair value gap 0.008; horizon 22:  238.73015688869575 191.00171954787533 0.4290474035656916 0.3560693496946064 345 353
fair value gap 0.008; horizon 24:  235.93045020753655 182.7631675915014 0.4367051393262467 0.32251114439332734 345 353
fair value gap 0.008; horizon 26:  252.56857875710168 164.5510248555241 0.5078071377011831 0.28721654236063926 345 353
fair value gap 0.008; horizon 28:  258.2350357744926 128.1273803711049 0.5321681969988582 0.25444334649394995 345 353
fair value gap 0.01; horizon 4:  196.86445041904776 200.05559990399993 0.4526073152836445 0.40606400445465113 210 225
fair value gap 0.01; horizon 6:  206.19091525904764 202.44019491111115 0.45756007858009873 0.38852236828413533 210 225
fair value gap 0.01; horizon 8:  187.6821625495239 191.07137414577767 0.35602959811292545 0.2974637062606915 210 225
fair value gap 0.01; horizon 10:  202.24039986095244 189.55599228444473 0.3112899967931605 0.2658758214734094 210 225
fair value gap 0.01; horizon 12:  198.66004990857175 213.80455422222252 0.30379957422971887 0.3405750751300305 210 225
fair value gap 0.01; horizon 14:  210.6945385419048 227.50218929955594 0.35076203573359765 0.36769008024206806 210 225
fair value gap 0.01; horizon 16:  242.97852563047633 176.2833730364444 0.4292282919778865 0.2436783167245681 210 225
fair value gap 0.01; horizon 18:  244.72813681619036 173.52837175111142 0.45941122991403044 0.2106812522236522 210 225
fair value gap 0.01; horizon 20:  229.5456992561904 179.6128011857781 0.40681742620990347 0.2541725280766196 210 225
fair value gap 0.01; horizon 22:  238.85492773904753 183.450110296889 0.469056837042427 0.2484799666098668 210 225
fair value gap 0.01; horizon 24:  237.87222784857187 157.196170920889 0.4778106965452221 0.1791384028638779 210 225
fair value gap 0.01; horizon 26:  243.19527511809545 113.20070754222232 0.5104235264547666 0.11404866959622595 210 225
fair value gap 0.01; horizon 28:  259.8769037466664 91.24173879111126 0.5362904150973509 0.08739059728515536 210 225
fair value gap 0.012; horizon 4:  159.59163715211315 197.43398733154368 0.38427133177179934 0.43745029504230204 142 149
fair value gap 0.012; horizon 6:  142.2306912929579 187.28831713422818 0.33135628376196197 0.37120997729797395 142 149
fair value gap 0.012; horizon 8:  114.7395232901411 161.68092156241602 0.19540738792410856 0.25361018917116956 142 149
fair value gap 0.012; horizon 10:  118.7206644549297 186.54507614765117 0.11959195358477036 0.30475829358262874 142 149
fair value gap 0.012; horizon 12:  90.07180239859184 226.43388279194676 0.07339279661001712 0.4276029478625897 142 149
fair value gap 0.012; horizon 14:  129.52527657746498 242.77966813020203 0.15310979591567708 0.4787437339099625 142 149
fair value gap 0.012; horizon 16:  151.59983803239462 206.27600053557043 0.23105355035452246 0.3821948021973488 142 149
fair value gap 0.012; horizon 18:  172.925354128169 188.06313471140936 0.2828137275253373 0.34105871959000383 142 149
fair value gap 0.012; horizon 20:  143.8564010323943 216.54371145503384 0.18868909621428254 0.4213127753160919 142 149
fair value gap 0.012; horizon 22:  161.21045207746474 238.6033939516782 0.26971735861558016 0.42198341866122435 142 149
fair value gap 0.012; horizon 24:  190.75991831690183 237.04621502281876 0.3380352356153374 0.3766790033238676 142 149
fair value gap 0.012; horizon 26:  161.0432985253525 211.59848655033582 0.35892461968982475 0.36229448659510294 142 149
fair value gap 0.012; horizon 28:  164.30670725070414 205.73801292617458 0.35519937656564965 0.3755259502751087 142 149
fair value gap 0.014; horizon 4:  151.8094992603778 131.87991827789514 0.38019191396034874 0.3010409018857426 106 95
fair value gap 0.014; horizon 6:  116.27596790188683 121.87496230526334 0.29723809886055375 0.24224767264104072 106 95
fair value gap 0.014; horizon 8:  81.77669419999981 109.46802022526306 0.12454244103167811 0.11097780386565911 106 95
fair value gap 0.014; horizon 10:  64.47662272264152 143.628058631579 0.00765502485201293 0.20200669038366595 106 95
fair value gap 0.014; horizon 12:  37.68286486415082 227.0510635684215 -0.020819575782353515 0.3797394313297587 106 95
fair value gap 0.014; horizon 14:  76.85546556603755 241.16591604631648 0.06309358279179457 0.42598787537317423 106 95
fair value gap 0.014; horizon 16:  118.55095274150966 231.53446698736795 0.16252889329418774 0.3328128575179102 106 95
fair value gap 0.014; horizon 18:  122.90834966226416 180.57854949473688 0.19622408638556207 0.2598157701058299 106 95
fair value gap 0.014; horizon 20:  99.54531209999975 149.82885869263214 0.10530395277383711 0.23397944170556378 106 95
fair value gap 0.014; horizon 22:  94.69423085849046 172.88825044210557 0.15506957460903759 0.23163715737165746 106 95
fair value gap 0.014; horizon 24:  139.07641856603811 201.61946123157892 0.23962463298533734 0.2042495965378834 106 95
fair value gap 0.014; horizon 26:  120.00170260000023 157.09425684210572 0.2848996093831068 0.15789818165510391 106 95
fair value gap 0.014; horizon 28:  125.52233341509418 167.15140202105272 0.29075729369969433 0.23085985015010796 106 95

In [253]:
pfvg_ret=nfvg_ret=pfvg=nfvg=pret_per=nret_per=0
pret=[]
nret=[]
for i in range(1,len(data)-16):
    if data['low'][i+1]-data['high'][i-1]>25:
        pfvg_ret+=data['close'][i+16]-data['close'][i]
        pfvg+=1
        pret_per+=(data['close'][i+16]-data['close'][i])/data['close'][i]
        pret.append(pfvg_ret)
    elif data['low'][i-1]-data['high'][i+1]>25:
        nfvg_ret+=data['close'][i]-data['close'][i+16]
        nfvg+=1
        nret_per+=(data['close'][i]-data['close'][i+16])/data['close'][i]
        nret.append(nfvg_ret)

In [254]:
nret

[-725.3007900000011,
 -669.1015700000062,
 -1061.9531300000017,
 -772.53125,
 -825.5390599999955,
 -643.8124949999983,
 -559.1601559999981,
 -665.9296859999959,
 -1222.160155999998,
 -143.7070259999964,
 52.05469400000584,
 -519.8945259999964,
 130.42187399999966,
 1730.5820329999988,
 4164.812492999998,
 6014.6328039999935,
 7343.453114999989,
 7893.816394999994,
 8514.917964999993,
 9129.335934999996,
 9157.164064999997,
 8702.886724999997,
 8298.664074999993,
 8187.683604999991,
 7799.835954999995,
 9048.316424999997,
 8858.867204999995,
 8432.328145,
 8319.839865000002,
 8605.128925000005,
 8409.976575,
 9675.988295000003,
 9766.207045000003,
 9025.609385000003,
 8315.492194000006,
 7594.472664000008,
 6702.98438400001,
 6349.816414000008,
 6164.804694000006,
 7263.1953240000075,
 8194.175794000002,
 8871.734394,
 9067.023454000002,
 8601.605484000007,
 8102.957054000006,
 7130.929714000005,
 7051.601584000004,
 7153.820344000007,
 7062.632844000007,
 6258.703164000006,
 6523.000034000004,
 6380.851594,
 6073.863314000002,
 5926.843784000004,
 6109.964884000001,
 6233.156283999997,
 6273.554724000001,
 5907.035194000004,
 6084.863314000002,
 6312.7344040000025,
 6515.726594000007,
 6719.574248000012,
 7565.933628000013,
 7232.8906590000115,
 6362.179719000007,
 6711.179719000007,
 9985.339879000006,
 13889.570348000008,
 17486.57034800001,
 19878.710968000007,
 21549.519558000007,
 22337.328148000008,
 22477.359398000008,
 23272.25782800001,
 24225.59767000001,
 25145.65626000001,
 25302.015640000012,
 26092.882820000013,
 26301.074220000017,
 26490.632810000017,
 26177.921870000013,
 25512.60156000001,
 24481.28124000001,
 24694.570300000007,
 24513.789050000007,
 24050.148420000005,
 24753.0078,
 25913.85546,
 27841.36327,
 29869.52343,
 27551.253900000003,
 28296.605461,
 28877.714835,
 29015.312495,
 29001.312495,
 28411.562495,
 27980.441404999998,
 27689.749995,
 26690.578114999997,
 25807.777335999992,
 24863.367175999992,
 25925.63670599999,
 28149.328105999986,
 30015.796850999985,
 31452.265602999985,
 31790.835912999988,
 31913.972633999983,
 31234.792943999986,
 30327.47263399999,
 30143.671853999986,
 29696.59372399999,
 29056.292943999993,
 27448.535133999998,
 27737.765601999992,
 28136.31247199999,
 28326.074191999993,
 27699.914031999993,
 27241.675753999996,
 27157.722623999995,
 27096.68356399999,
 26999.253873999995,
 27029.054653,
 26516.804653,
 26516.312472999998,
 26325.011693,
 26522.499972999998,
 26720.289042999997,
 26764.175752999996,
 27612.445285,
 28135.94528,
 28625.31246,
 28391.320269999997,
 27748.730424,
 27089.757764,
 26848.320264,
 26692.277294,
 26740.109324000005,
 26572.429634000007,
 27177.558534000003,
 28689.917904,
 29300.417904,
 29753.777274,
 29972.097583999996,
 29809.499923999996,
 29722.050703999994,
 29353.519453999994,
 28906.910078999994,
 28174.58976899999,
 24972.507738999986,
 24891.93742899999,
 24941.558528999994,
 24698.910098999993,
 24901.851508999993,
 24674.980408999996,
 24467.121028999994,
 24577.917898999993,
 24274.589778999994,
 23450.351498999997,
 22426.421811,
 23068.503851,
 22870.714791000006,
 21822.476510000008,
 20615.04682000001,
 21082.718690000016,
 20792.585880000013,
 20755.015560000014,
 20037.16400000001,
 18838.402280000017,
 18854.38274900002,
 20277.91008900002,
 21382.70696400002,
 21921.42571400002,
 22066.87493400002,
 21484.714774000022,
 21744.855404000024,
 21921.468694000025,
 21956.546814000023,
 22120.980413000027,
 21704.980413000027,
 21599.570263000023,
 21757.242142000025,
 22036.03120200002,
 22268.84370200002,
 22007.45307200002,
 21591.484332000022,
 20271.535122000023,
 20199.10543200002,
 19972.714812000013,
 19629.98433800001,
 19202.07417800001,
 19682.496048000015,
 19621.175738000013,
 20057.468708000015,
 21859.32026800001,
 23386.613238000013,
 24652.62105000001,
 27017.78902000001,
 28580.917920000007,
 28801.257760000008,
 29168.988228000002,
 28770.570258,
 28900.968697999997,
 28935.621048,
 30604.089787999997,
 32326.929637999994,
 33954.99995799999,
 35278.39057799999,
 36428.55854799999,
 37259.30854799999,
 37861.37885799999,
 37738.73823799999,
 36794.08589799999,
 38137.11323799999,
 38448.003858,
 39460.074177999995,
 40026.902308,
 39503.472618,
 40734.355434,
 41219.644503999996,
 40293.324194,
 39833.355454000004,
 38790.976545000005,
 37602.83982500001,
 38653.99998500001,
 39854.55857700001,
 40954.14841700001,
 41877.85544700001,
 44715.437477000014,
 47389.687477000014,
 48664.406227000014,
 49517.093727000014,
 49955.484357000016,
 49470.75388700001,
 48770.80466700001,
 47925.52732700001,
 47101.28904700001,
 46169.636697000016,
 46581.968727000014,
 46699.44138700001,
 46286.27341700001,
 46746.343727000014,
 47241.72263100002,
 47258.714821000016,
 46693.50388100001,
 48357.92185000001,
 49126.21091200002,
 48882.04294200002,
 48507.992162000024,
 44854.61326200003,
 44772.58592200003,
 44640.88279600003,
 44235.65623600003,
 43976.91404600003,
 43290.62497600003,
 43504.54685600003,
 43469.70701600003,
 43993.03514100003,
 43947.08592100003,
 44863.61717100003,
 45442.70701600003,
 45550.81639600003,
 45032.50389700003,
 44310.945297000035,
 41168.824207000034,
 41273.09373700003,
 42510.91013700003,
 44820.24216700003,
 46637.882797000035,
 47683.753887000035,
 47894.24216700003,
 47762.67185700003,
 47355.12106700003,
 47881.57028700003,
 47414.05075700003,
 46730.55075700003,
 47482.74216700003,
 47250.24216700003,
 46823.972637000035,
 46865.48044700004,
 46869.01169700004,
 46684.30075700003,
 46315.859347000034,
 46346.722637000035,
 46222.355457000034,
 46021.30467800003,
 46710.703118000034,
 46713.84373800004,
 45749.632798000035,
 45743.492174000035,
 45480.433584000035,
 45821.613264000036,
 45052.84373400003,
 44306.22264400003,
 42951.42186400003,
 42080.050764000036,
 40853.269514000036,
 40835.32029400004,
 40772.07029400004,
 40443.28904400004,
 39133.34763400004,
 39360.51950400004,
 39167.527314000035,
 39690.968724000035,
 39901.26559400003,
 39800.804654000036,
 39488.23434400003,
 38932.94528400003,
 38579.863254000025,
 38258.265594000026,
 37032.894504000025,
 36255.253874000024,
 36510.42183400002,
 36881.33199400002,
 37412.20308400002,
 37612.335894000025,
 37852.57417400002,
 37711.12104400002,
 37467.00386400002,
 37108.35542400002,
 36689.503854000024,
 36005.48041400002,
 35702.47260400002,
 35341.23432400002,
 35448.023384000015,
 35112.773384000015,
 34473.476514000016,
 34730.79682400001,
 34482.29682400001,
 34295.554638000016,
 34303.37494800002,
 34536.24212800002,
 34450.63275800002,
 34280.91400800002,
 34156.06634700002,
 35508.41400700002,
 36663.65229100002,
 37229.24213100002,
 37571.925730000024,
 37782.03510000002,
 39063.12495000003,
 39018.86713000003,
 38865.406191000024,
 38356.70697100002,
 37449.12494100002,
 36528.87494100002,
 36357.79290600002,
 37028.88275600002,
 37182.73041600002,
 37018.36712600002,
 37428.07415600002,
 37951.49212100002,
 38331.29291100002,
 38104.16400100002,
 37302.28118500002,
 36184.011655000024,
 34934.71086500002,
 35516.67961500002,
 35576.75773500002,
 36148.57023500002,
 36347.288995000024,
 35887.32805500002,
 37025.84758500002,
 38060.26555500002,
 38457.347587000026,
 39369.80071700003,
 39663.101497000025,
 39771.05852700002,
 39754.80852700002,
 39484.66008700002,
 40062.402277000016,
 40377.82415700002,
 40803.40618700002,
 40948.06634700002,
 41970.046817000024,
 42549.23821700003,
 42853.050713000026,
 42894.14056300003,
 42587.91790500003,
 43451.65618300003,
 43956.84368300003,
 44195.90618300003,
 44775.06633300003,
 45347.28508300003,
 46891.71477300003,
 48036.085873000025,
 49192.996033000025,
 49606.706963000026,
 49262.12493300002,
 48740.86711300002,
 49444.347583000024,
 49699.33977300002,
 49721.33977300002,
 48995.031175000026,
 48770.531175000026,
 48256.441336000025,
 46883.222586000025,
 48172.44133100002,
 48821.82415100002,
 48828.42181100002,
 48505.121031000024,
 48294.288996000025,
 47894.179625000026,
 47884.460875000026,
 47657.968695000025,
 47513.26947500002,
 47989.628855000024,
 49422.26947500003,
 50429.92181500003,
 51128.86322500003,
 50827.14447300003,
 49193.59760300003,
 49293.195253000034,
 49331.05462300003,
 49322.722593000035,
 49168.90228400003,
 49319.60931400003,
 49399.76947400003,
 49164.28900400003,
 48666.058534000025,
 48466.371032000025,
 47238.48040200002,
 48891.24993200002,
 50350.99993200002,
 51074.10931200002,
 51638.37884200002,
 51635.83197200002,
 51523.22259200003,
 51253.20306200003,
 51186.91009600003,
 51356.167906000024,
 51502.39056400002,
 51183.56243400002,
 51840.413994000024,
 52239.18352400002,
 52725.304624000026,
 52297.976494000024,
 51552.05852400002,
 53406.57023900002,
 55599.51945900002,
 57105.71867900002,
 58324.28117900002,
 59320.21867900002,
 59758.83585900002,
 59373.449139000026,
 58760.56632900002,
 58144.507729000026,
 58682.42959900003,
 59382.328038000036,
 60301.328038000036,
 60881.14834800004,
 61150.76943900004,
 61008.01943900004,
 61120.937409000035,
 61783.32021900004,
 61554.968659000035,
 61528.17178900004,
 61397.394449000036,
 61064.21475900003,
 60397.48429900003,
 60096.644449000036,
 60546.42179900003,
 60545.992109000035,
 60916.66007900004,
 61389.25773900004,
 61590.429609000035,
 61299.929609000035,
 60268.93741900003,
 63312.445229000026,
 66098.09366900002,
 68241.03506900002,
 69879.61709900002,
 70342.76553100003,
 70689.12490100003,
 70606.47255100003,
 70770.06239100003,
 71049.38270100002,
 70944.81239100001,
 70692.22255100001,
 71848.35145100001,
 72825.91005100001,
 73644.05848100001,
 74056.00770100002,
 74327.17958100003,
 74215.21083100003,
 74040.70301900004,
 74608.33191900003,
 75182.99207900003,
 75436.66395900003,
 76299.47450900002,
 78421.51356900002,
 80265.76356900002,
 81677.62293900002,
 82820.28309900002,
 82611.30262900001,
 81281.57215900002,
 79697.50379900003,
 78962.67371900003,
 79881.12488900003,
 80203.89442900004,
 80263.56434900004,
 79403.07411900003,
 78229.70497340002,
 79203.74598340002,
 81367.52528340001,
 82358.69520340001,
 83225.14637340001,
 84296.42567340001,
 84950.8358344,
 85413.8553644,
 85425.9256744,
 85179.2655144,
 83642.54676540001,
 82763.2459854,
 83843.9452054,
 83768.8358354,
 84084.18544539998,
 84014.37490539998,
 84265.92568539997,
 83811.09561239998,
 83281.19522239998,
 83098.31631239998,
 82387.88467239999,
 81945.81435239999,
 80709.29482139999,
 79953.3045914,
 81318.8338814,
 82444.40419140001,
 83081.65418840002,
 83300.03309840002,
 83019.09169140001,
 82249.7401314,
 82222.4998914,
 81932.30067140001,
 81357.6795814,
 81847.9002914,
 82012.1600614,
 82093.1600614,
 82614.9413014,
 83182.1815414,
 83491.8319324,
 83739.0721724,
 83503.20303240001,
 82352.17178240001,
 82115.08194240001,
 82158.55264800001,
 82835.77139800001,
 83141.79092800002,
 83170.06046800001,
 83111.69133000002,
 82718.44133000002,
 81971.12102100001,
 82031.88274200002,
 81362.96282200002,
 80975.503842,
 80960.013602,
 82066.91399200002,
 83047.57414900002,
 83651.52336900003,
 83608.17375900003,
 83351.37297900004,
 82671.70305900004,
 82372.53313340004,
 82526.79485340003,
 82368.18547340002,
 82206.11516340003,
 81982.74601340003,
 81526.62687340003,
 80965.51555340004,
 81040.52532340004,
 81005.67376340003,
 80979.51361340003,
 80833.79486340003,
 80601.86517340003,
 80534.32611340003,
 80208.34564340004,
 79927.18548240003,
 78746.26555800003,
 77397.36711800002,
 76572.66789800001,
 76521.00773800001,
 76550.62882800002,
 76428.29874800002,
 77690.61905900002,
 79409.91983900002,
 80874.23037900002,
 81866.30068900003,
 82798.79092900002,
 83482.71084900002,
 83803.83194900003,
 83630.85148000003,
 84331.26164000003,
 84781.79094000004,
 85039.78118000003,
 84779.99211800004,
 84823.43156800003,
 84688.07023800003,
 84602.74992800003,
 84652.29876000003,
 84182.86908000003,
 82915.99994000004,
 84060.40033000003,
 84596.33001900003,
 84892.44915900003,
 84904.13861900003,
 83999.84955900004,
 84587.02924900004,
 84396.79877900003,
 84472.35737900002,
 84751.16792900002,
 84832.56636900001,
 84637.73628900001,
 85058.32612900001,
 84766.87690900001,
 85712.19722900001,
 86389.47847900001,
 86692.67769500002,
 87689.29683400002,
 88724.68550500003,
 89479.75581500003,
 89842.65620500004,
 89712.49604500004,
 89712.13667500003,
 89577.20699500003,
 91774.35738500002,
 94002.25582500003,
 95822.89645100004,
 97661.82614100003,
 99526.75583100002,
 101369.57614100001,
 102753.19528100001,
 104257.91403100001,
 104706.31442100002,
 105127.71286300002,
 107243.05270200002,
 109172.61130200002,
 110427.75192200002,
 110708.50192200002,
 110736.25192200002,
 110402.51169200003,
 109632.94138200003,
 108340.00193200004,
 108656.35154200005,
 108471.69138200005,
 108280.59958200005,
 108609.92966200005,
 109528.83981900006,
 110207.53122900006,
 110962.09177900005,
 111310.86130900006,
 111117.61130900006,
 110425.47068900005,
 108491.18943900005,
 109577.66014200005,
 110500.17967000006,
 111309.65037000005,
 111289.69138000005,
 111664.12107000005,
 111166.55075800006,
 110629.99021800005,
 110607.33006240005,
 110626.07029240005,
 110683.09959240005,
 110741.66990240004,
 112042.86131240004,
 112382.84177240005,
 112284.89060240005,
 112473.97068240005,
 112436.19138240005,
 111719.12302040006,
 111629.36326040006,
 111073.55271040005,
 109671.21287140006,
 108716.50388340006,
 108572.01364940006,
 108064.37302940006,
 107086.14255940006,
 107325.59177940007,
 107336.21286940007,
 106986.91403940007,
 106281.65231940008,
 106355.33395940007,
 107151.39450940007,
 107738.04294940006,
 107743.15231940006,
 107555.01364940006,
 106767.95309940007,
 107128.09372040007,
 107223.86521040006,
 107049.62497340006,
 106648.40622040007,
 106408.82614040007,
 105642.17575040006,
 105291.69528040005,
 105052.98630040005,
 104683.12693040006,
 104529.52732040006,
 104658.21872040007,
 104581.34958040007,
 104572.75974040007,
 104622.34958040007,
 104652.61911240008,
 104770.27926240009,
 104854.16012340008,
 104732.83004340008,
 105166.25973340009,
 105471.6093434001,
 105386.6991934001,
 105850.1894234001,
 106311.6093534001,
 106349.7792734001,
 106502.25974340009,
 106849.87106340009,
 107787.74020340008,
 108094.28122340009,
 108206.61130340009,
 108277.9804434001,
 106958.32224340009,
 108174.8808334001,
 109120.4706814001,
 109683.2617014001,
 109820.2421714001,
 109450.5429514001,
 109385.5839614001,
 109534.59373140009,
 109724.9921714001,
 109325.7421714001,
 108915.4120914001,
 109711.9804514001,
 110107.4199014001,
 110428.8495914001,
 110436.1894314001,
 109557.7089594001,
 109542.3085694001,
 109237.4589594001,
 109132.0898194001,
 108873.39059940011,
 109100.49997140012,
 109681.43942140011,
 110282.31051140011,
 110027.74996700011,
 109574.45113700011,
 109607.78121500011,
 109819.84175500012,
 109775.07222100013,
 109583.73237800013,
 109884.59369800013,
 110218.35346800013,
 110163.88471900014,
 110243.30463900014,
 110271.86518900013,
 110529.00581300014,
 110860.61714100014,
 110898.21870200014,
 110937.97846400015,
 111078.12885400014,
 111633.17963400015,
 112045.86908400015,
 112367.07025400015,
 112652.67963300015,
 112862.24018200015,
 113037.97065200016,
 113211.58979400016,
 113392.10151500016,
 113517.88081600016,
 113236.96089400016,
 113455.38082400017,
 113327.66207500017,
 112827.17183500018,
 113265.93159940018,
 112796.23237940019,
 112590.33393940018,
 112192.82416940018,
 111790.84369940017,
 111762.29291640017,
 111948.78315640017,
 111794.97260640017,
 111539.13276640017,
 111653.07222640017,
 111525.70112640016,
 111365.18158640017,
 111814.16205640018,
 112067.74213640018,
 112038.30072640018,
 111708.23041640018,
 110299.27142640018,
 110796.71087640019,
 110670.58001640018,
 110160.34955640018,
 110057.18939640018,
 109160.95892640017,
 108363.52923640017,
 108925.91009640017,
 109373.91009640017,
 109674.16986640016,
 110185.33978640016,
 110306.26947640016,
 110190.87884640017,
 110122.02923840017,
 109559.75970840018,
 109451.58001840019,
 109104.02923840018,
 109792.41009840017,
 110401.43939480017,
 110824.72846480017,
 111042.14838480017,
 110797.53900480017,
 111207.08783480017,
 111633.60736480018,
 111587.95892480017,
 111206.79876480017,
 111007.76751480017,
 110779.52728480016,
 111026.50775480016,
 111548.16790780016,
 111814.60735880016,
 112024.18743880016,
 112046.58782880015,
 111952.91790780015,
 112751.13665680014,
 113635.90618680014,
 114130.71673680014,
 114377.90618680013,
 114393.10735780012,
 114216.62688780011,
 114208.57610780011,
 113694.99603380011,
 113651.33587380011,
 113597.6561838001,
 113453.05657180012,
 114123.57805180011,
 114288.53898180011,
 114188.97062180011,
 114451.11125180012,
 114579.21086180012,
 114439.60149180013,
 114796.80266380013,
 114868.94328940014,
 114803.29289940014,
 114651.96281940014,
 114936.26359940015,
 114970.59172140015,
 114394.70305140015,
 114789.42375040015,
 115019.31437040016,
 114654.03507140015,
 114596.58585140016,
 114791.20499140015,
 115017.46475140016,
 115060.25576580016,
 114851.01552580016,
 114844.27529580017,
 114801.21475580017,
 115005.30655580017,
 115170.41593480017,
 115198.03702480017,
 114951.86514480016,
 114593.83584780016,
 114599.90420780017,
 114801.66396780017,
 114773.97256780017,
 115351.91202780016,
 115801.32218780016,
 116163.62296780017,
 116381.35148780017,
 116254.31046780017,
 116278.06046780017,
 115933.74991780016,
 115382.74015780016,
 114683.66008780016,
 114743.38860080016,
 115399.30852080016,
 115676.24016080017,
 115632.00969080017,
 115463.02922080018,
 115065.12883080018,
 114599.06047080018,
 114529.56047080018,
 114867.66008080018,
 115141.04875080018,
 115063.76945080019,
 115361.2499108002,
 115322.07998080019,
 115409.0194308002,
 115378.2088808002,
 115389.8084908002,
 115359.3084908002,
 115983.8592708002,
 116405.5291908002,
 116517.7088808002,
 116341.7303608002,
 116690.8495018002,
 117907.4608318002,
 119100.7303618002,
 120110.1405208002,
 120678.4706008002,
 120921.8006808002,
 120964.70107080019,
 120876.03115180018,
 120853.41982180018,
 120695.36904080019,
 120383.10927480018,
 120171.78895480018,
 120346.26942480018,
 120279.30848480017,
 119970.39832480018,
 119883.13855480017,
 119810.83777480017,
 119685.25770080017,
 119464.37879080017,
 119149.56825080016,
 118613.19911080017,
 118649.15028080017,
 118495.21082080016,
 118118.46082080016,
 118050.96082080016,
 117653.32019080015,
 118172.42957080016,
 118964.82996080015,
 119507.41980080015,
 120046.27136080016,
 120101.41003080017,
 120176.41003080017,
 120110.67175080016,
 120015.28113080017,
 119921.74207080017,
 119570.01160080018,
 119313.06238080018,
 119675.26355080018,
 119981.61316080019,
 119883.56432780018,
 119535.83385780019,
 119557.12291980018,
 119520.93346420018,
 119607.70299320018,
 119550.02330220018,
 119186.61315220018,
 119310.55260220019,
 119223.82213420019,
 119299.5330642002,
 119312.5428342002,
 119138.5819022002,
 119205.1131522002,
 119205.7225312002,
 119164.13073120019,
 119134.61120120018,
 119008.04088120018,
 119777.76158120019,
 120043.79282120019,
 119898.10142120019,
 119695.19126120019,
 119585.2010312002,
 119351.7615812002,
 119411.83189120021,
 119452.47251220021,
 119488.23228120021,
 119316.40220120021,
 120545.45103120021,
 121620.19127120021,
 122399.39243920021,
 122213.85336920021,
 122043.4627492002,
 122278.1736862002,
 122173.5525962002,
 122188.4607962002,
 122154.7908762002,
 122189.5408762002,
 122172.00181620021,
 122164.9412762002,
 122113.0213562002,
 122632.9412762002,
 122888.00963620021,
 123568.51939620021,
 123812.45884620021,
 123162.57798620021,
 122654.6482962002,
 122891.19907820021,
 122925.33774820021,
 122776.49790720022,
 122831.27915720022,
 123160.21861720021,
 123368.71861720021,
 123158.9178372002,
 122919.5272172002,
 123244.6580772002,
 122897.5975372002,
 122843.7069072002,
 122832.38659720021,
 122892.8182372002,
 122594.04870720021,
 122322.91980720022,

In [460]:
# Unmitigated
horizons=[4,6,8,10,12,14,16,20,24,28,32]
for h in horizons:
    pfvg_ret=nfvg_ret=pfvg=nfvg=pret_per=nret_per=0
    pret=[]
    nret=[]
    for i in range(1,len(data)-8):
        if (data['low'][i+1]-data['high'][i-1])/data['close'][i]>0.001:
            mitigated=False 
            for j in range(i+2,i+h):
                if data['close'][j]<data['low'][i+1]:
                    mitigated=True
                    break
            if not mitigated:
                pfvg_ret+=data['close'][i+16]-data['close'][i]
                pfvg+=1
                pret_per+=(data['close'][i+16]-data['close'][i])/data['close'][i]
                pret.append(data['close'][i+16]-data['close'][i])
        elif (data['low'][i-1]-data['high'][i+1])/data['close'][i]>0.001:
            mitigated=False
            for j in range(i+2,i+h):
                if data['close'][j]>data['high'][i+1]:
                    mitigated=True
                    break
            if not mitigated:
                nfvg_ret+=data['close'][i]-data['close'][i+16]
                nfvg+=1
                nret_per+=(data['close'][i]-data['close'][i+16])/data['close'][i]
                nret.append(data['close'][i]-data['close'][i+16])
    print(f'horizon {h}: ',pfvg_ret/pfvg,nfvg_ret/nfvg,pret_per*100/pfvg,nret_per*100/nfvg,pfvg,nfvg,sum(1 for x in pret if x<0)/pfvg,sum(1 for x in nret if x<0)/nfvg)

horizon 4:  299.36368867519934 314.15628748649124 0.5953654227324817 0.5581314249006045 2504 2243 0.34584664536741216 0.3727151136870263
horizon 6:  425.0037559535995 446.5227701803921 0.8401778238889883 0.8154498892010614 2028 1785 0.28155818540433925 0.29523809523809524
horizon 8:  513.0338863164101 549.5959360562058 1.0102597569456968 1.004187902365958 1755 1555 0.23304843304843303 0.24115755627009647
horizon 10:  603.0455903199223 634.7759855895266 1.1767549017679 1.1576216865337747 1556 1394 0.18766066838046272 0.18794835007173602
horizon 12:  682.0237456088912 695.0713078319001 1.3201951230405784 1.2753637905499808 1417 1279 0.14114326040931546 0.1485535574667709
horizon 14:  747.3116527907569 748.2794617127487 1.4435796852462617 1.3700880369027182 1320 1208 0.10681818181818181 0.11423841059602649
horizon 16:  828.7635069452317 821.406885659768 1.6027616520361954 1.5101843599666236 1227 1121 0.05378973105134474 0.06333630686886708
horizon 20:  900.1598530391766 887.6185854913174 1.7417290342751832 1.6358408892644023 1118 1025 0.024150268336314847 0.03414634146341464
horizon 24:  935.9653009572515 924.8599954590726 1.8057739113279312 1.710058149223543 1048 948 0.02194656488549618 0.028481012658227847
horizon 28:  964.6853955636178 958.2789930709237 1.8639158121714743 1.7689123813562917 984 877 0.02032520325203252 0.026225769669327253
horizon 32:  986.1556802729785 984.6417260063655 1.9062917385695612 1.8261515662849717 940 817 0.019148936170212766 0.02692778457772338

In [441]:
pfvg_ret=nfvg_ret=pfvg=nfvg=pret_per=nret_per=0
pret=[]
nret=[]
for i in range(1,len(data)-16):
    if data['low'][i+1]-data['high'][i-1]>25:
        mitigated=False 
        for j in range(i+2,i+8):
            if data['close'][j]<data['low'][i+1]:
                mitigated=True
                break
        if not mitigated:
            pfvg_ret+=data['close'][i+16]-data['close'][i]
            pfvg+=1
            pret_per+=(data['close'][i+16]-data['close'][i])/data['close'][i]
            pret.append(pfvg_ret)
    elif data['low'][i-1]-data['high'][i+1]>25:
        mitigated=False
        for j in range(i+2,i+8):
            if data['close'][j]>data['high'][i+1]:
                mitigated=True
                break
        if not mitigated:
            nfvg_ret+=data['close'][i]-data['close'][i+16]
            nfvg+=1
            nret_per+=(data['close'][i]-data['close'][i+16])/data['close'][i]
            nret.append(nfvg_ret)

In [442]:
sum(1 for x in pret if x<0)

0

In [ ]:
# Consolidating 
pfvg_ret=nfvg_ret=pfvg=nfvg=pret_per=nret_per=0
pret=[]
nret=[]
for i in range(1,len(data)-24):
    if data['low'][i+1]-data['high'][i-1]>300:
        consolidating=False
        if data['abs_body'][i+1]<50:
            consolidating=True 
        if consolidating:
            pfvg_ret+=data['close'][i+24]-data['close'][i]
            pfvg+=1
            pret_per+=(data['close'][i+24]-data['close'][i])/data['close'][i]
            pret.append(pfvg_ret)
    elif data['low'][i-1]-data['high'][i+1]>200:
        consolidating=False
        if data['abs_body'][i+1]<25:
            consolidating=True
        if consolidating:
            nfvg_ret+=data['close'][i]-data['close'][i+12]
            nfvg+=1
            nret_per+=(data['close'][i]-data['close'][i+12])/data['close'][i]
            nret.append(nfvg_ret)

In [377]:
pfvg_ret/pfvg,nfvg_ret/nfvg,pfvg,nfvg

(45.25647218185087, 195.13343547435966, 1113, 78)

In [286]:
sum(1 for x in nret if x<0)

0

In [487]:
# Inversion FVG
pfvg_ret=nfvg_ret=pfvg=nfvg=pret_per=nret_per=0
pret=[]
nret=[]
for i in range(1,len(data)-12):
    if data['low'][i+1]-data['high'][i-1]>100:
        ifvg=False
        for j in range(i+4,i+12):
            if data['low'][j-1]-data['high'][j+1]>200:
                ifvg=True
                break
        if ifvg:
            pfvg_ret+=data['close'][i+24]-data['close'][j+1]
            pfvg+=1
            pret_per+=(data['close'][i+24]-data['close'][j+1])/data['close'][j+1]
            pret.append(pfvg_ret)
    elif data['low'][i-1]-data['high'][i+1]>100:
        ifvg=False
        for j in range(i+4,i+12):
            if data['low'][j+1]-data['high'][j-1]>200:
                ifvg=True 
                break
        if ifvg:
            nfvg_ret+=data['close'][j+1]-data['close'][i+24]
            nfvg+=1
            nret_per+=(data['close'][j+1]-data['close'][i+24])/data['close'][j+1]
            nret.append(nfvg_ret)

In [488]:
pfvg_ret/pfvg,nfvg_ret/nfvg,pfvg,nfvg

(118.81598058263343, 90.28549785770473, 357, 305)

In [ ]:
sum(1 for x in pret if x<0)

21

In [491]:
# Reaction
horizons=[2,4,8,12,16,20,24,28,32]
for h in horizons:
    pfvg_ret=nfvg_ret=pfvg=nfvg=pret_per=nret_per=0
    for i in range(1,len(data)-h):
        if data['low'][i+1]-data['high'][i-1]>25:
            reaction=True  
            for j in range(i+2,i+h):
                if data['close'][j]<data['high'][i-1]:
                    reaction=False
            if reaction:
                pfvg_ret+=data['close'][i+h]-data['close'][i]
                pfvg+=1
                pret_per+=(data['close'][i+h]-data['close'][i])/data['close'][i]
        elif data['low'][i-1]-data['high'][i+1]>25:
            reaction=True 
            for j in range(i+2,i+h):
                if data['close'][j]>data['low'][i-1]:
                    reaction=False
            if reaction:
                nfvg_ret+=data['close'][i]-data['close'][i+h]
                nfvg+=1
                nret_per+=(data['close'][i]-data['close'][i+h])/data['close'][i]
    print(f'horizon {h}: ',pfvg_ret/pfvg,nfvg_ret/nfvg,pret_per*100/pfvg,nret_per*100/nfvg,pfvg,nfvg)

horizon 2:  105.73175283322213 110.15522198866215 0.18737913964590383 0.18996211693836104 4795 4410
horizon 4:  197.56004936684138 210.94723785323865 0.3443719565457301 0.3581326490137927 4005 3659
horizon 8:  375.1844627429502 389.78554742069196 0.6695932629358876 0.6633831923072663 3064 2774
horizon 12:  526.9493965451913 537.8739066951125 0.935385767295921 0.9111296512850424 2558 2332
horizon 16:  670.1179091802916 645.5924304545277 1.1905380583174903 1.0900603735873093 2263 2054
horizon 20:  771.7594435463272 755.5414067481751 1.3783117487568513 1.2821614012210065 2055 1864
horizon 24:  880.9672990447233 873.3168351237914 1.567135162616811 1.4974518229622327 1914 1719
horizon 28:  970.8598184281263 942.9802083860244 1.7496747402046802 1.645521692466411 1799 1603
horizon 32:  1063.4874505244763 1003.1338143819273 1.9112239996718667 1.7685447470829259 1716 1494

In [492]:
pfvg_ret=nfvg_ret=pfvg=nfvg=pret_per=nret_per=0
pret=[]
nret=[]
for i in range(1,len(data)-4):
    if data['low'][i+1]-data['high'][i-1]>25:
        reaction=True  
        for j in range(i+2,i+4):
            if data['close'][j]<data['high'][i-1]:
                reaction=False
        if reaction:
            pfvg_ret+=data['close'][i+4]-data['close'][i]
            pfvg+=1
            pret_per+=(data['close'][i+4]-data['close'][i])/data['close'][i]
            pret.append(pfvg_ret)
    elif data['low'][i-1]-data['high'][i+1]>25:
        reaction=True 
        for j in range(i+2,i+4):
            if data['close'][j]>data['low'][i-1]:
                reaction=False
        if reaction:
            nfvg_ret+=data['close'][i]-data['close'][i+4]
            nfvg+=1
            nret_per+=(data['close'][i]-data['close'][i+4])/data['close'][i]
            nret.append(nfvg_ret)

In [495]:
len(pret)

4005

In [496]:
sum(1 for x in pret if x<0)

7

In [1]:
# Support/Resistance
horizons=[4,5,6,7,8]
for h in horizons:
    pfvg_ret=nfvg_ret=pfvg=nfvg=pret_per=nret_per=0
    for i in range(h,len(data)-h):
        if data['low'][i+1]-data['high'][i-1]>25:
            support=False
            for j in range(2,h):
                if data['high'][i-1]<data['high'][i-j]<data['low'][i+1]:
                    support=True
                if data['high'][i-j]>data['low'][i+1]:
                    support=False
                    break
            if support:
                pfvg_ret+=data['close'][i+h]-data['close'][i]
                pfvg+=1
                pret_per+=(data['close'][i+h]-data['close'][i])/data['close'][i]
        elif data['low'][i-1]-data['high'][i+1]>25:
            resistance=False
            for j in range(2,h):
                if data['high'][i+1]<data['low'][i-j]<data['low'][i-1]:
                    resistance=True 
                if data['low'][i-j]<data['high'][i+1]:
                    resistance=False
                    break
            if resistance:
                nfvg_ret+=data['close'][i]-data['close'][i+h]
                nfvg+=1
                nret_per+=(data['close'][i]-data['close'][i+h])/data['close'][i]
    print(f'horizon {h}: ',pfvg_ret/pfvg,nfvg_ret/nfvg,pret_per*100/pfvg,nret_per*100/nfvg,pfvg,nfvg)

NameError: name 'data' is not defined

In [499]:
pfvg_ret=nfvg_ret=pfvg=nfvg=pret_per=nret_per=0
pret=[]
nret=[]
for i in range(7,len(data)-7):
    if data['low'][i+1]-data['high'][i-1]>25:
        support=False
        for j in range(2,5):
            if data['high'][i-1]<data['high'][i-j]<data['low'][i+1]:
                support=True
            if data['high'][i-j]>data['low'][i+1]:
                support=False
                break
        if support:
            pfvg_ret+=data['close'][i+5]-data['close'][i]
            pfvg+=1
            pret_per+=(data['close'][i+5]-data['close'][i])/data['close'][i]
            pret.append(pfvg)
    elif data['low'][i-1]-data['high'][i+1]>25:
        resistance=False
        for j in range(2,7):
            if data['high'][i+1]<data['low'][i-j]<data['low'][i-1]:
                resistance=True 
            if data['low'][i-j]<data['high'][i+1]:
                resistance=False
                break
        if resistance:
            nfvg_ret+=data['close'][i]-data['close'][i+7]
            nfvg+=1
            nret_per+=(data['close'][i]-data['close'][i+7])/data['close'][i]
            nret.append(nfvg)

In [501]:
sum(1 for x in nret if x<0)

0

In [267]:
# Priority
for h in range(1,21):
    pfvg_ret=nfvg_ret=pfvg=nfvg=pret_per=nret_per=0
    i=1
    while i<len(data)-20:
        if data['low'][i+1]-data['high'][i-1]>25:
            pfvg_ret+=data['close'][i+20]-data['close'][i]
            pfvg+=1
            pret_per+=(data['close'][i+20]-data['close'][i])/data['close'][i]
            i+=h-1
        elif data['low'][i-1]-data['high'][i+1]>25:
            nfvg_ret+=data['close'][i]-data['close'][i+20]
            nfvg+=1
            nret_per+=(data['close'][i]-data['close'][i+20])/data['close'][i]
            i+=h-1
        i+=1
    print(f'horizon {h}: ',pfvg_ret/pfvg,nfvg_ret/nfvg,pret_per*100/pfvg,nret_per*100/nfvg,pfvg,nfvg)

horizon 1:  122.70849428745252 112.82528749886066 0.23016111923997895 0.1861481598328795 4774 4388
horizon 2:  117.30052814432987 102.34744412439485 0.21497409625252262 0.170416725928337 3986 3677
horizon 3:  113.49175710957292 88.04272656354836 0.20361254046238023 0.13763662468809676 3562 3303
horizon 4:  98.29137171764498 77.82484877634892 0.19416717734719832 0.11919554888109396 3236 3002
horizon 5:  96.69027594178188 79.50526444028033 0.19352484357650776 0.11560651626369524 2963 2711
horizon 6:  97.56947957749516 78.06108113863992 0.18977071732561362 0.12086228304917106 2715 2500
horizon 7:  110.3901351884859 89.17594455999989 0.21067594217157481 0.13493523202208407 2510 2335
horizon 8:  102.88148364580469 83.34657768548993 0.20205930091203275 0.12708609649820457 2336 2164
horizon 9:  103.8784698205692 79.30877158270748 0.2219812969855832 0.1119406348725387 2178 2024
horizon 10:  81.97945837113978 72.46026997961573 0.18897781901204141 0.11586786758922617 2079 1874
horizon 11:  98.33501233678786 67.62895184668912 0.2113436005450372 0.11048367087555434 1949 1782
horizon 12:  106.53282455159525 73.6657986414123 0.217676969704056 0.12013488278271965 1849 1671
horizon 13:  82.80655145635968 60.04908354892548 0.19001264687955008 0.11394954056735566 1769 1582
horizon 14:  113.5004760806609 83.07468572549031 0.22747977630255095 0.1296023445583223 1665 1530
horizon 15:  107.37195531920675 78.86265679986413 0.22139416122630068 0.11583639973234958 1588 1472
horizon 16:  98.30463220834957 86.46120507337187 0.20022888989889412 0.13164642894922085 1545 1382
horizon 17:  96.57507918559648 77.72103574631971 0.1968637081372145 0.1307939641896722 1458 1345
horizon 18:  127.67746456135174 75.38375348275858 0.25113203326288336 0.12619335357685077 1361 1334
horizon 19:  110.15126209468069 78.80649981797053 0.21325801742607797 0.11113548414647345 1316 1291
horizon 20:  109.49602293662738 74.69151778749001 0.22319755228093344 0.11730228976687553 1275 1247

In [360]:
def find_recent_swing_range(data):
    highs=[]
    lows=[]
    for i in range(5,len(data)-5):
        window=data.iloc[i-5:i+6]
        if data["high"].iloc[i]==window["high"].max():
            highs.append((i,data["high"].iloc[i]))
        if data["low"].iloc[i]==window["low"].min():
            lows.append((i,data["low"].iloc[i]))
    if not highs or not lows:
        return None,None
    recent_high=highs[-1][1]
    recent_low=lows[-1][1]
    return recent_high,recent_low

In [435]:
# Break of structure and Liquidity
pfvg_ret=nfvg_ret=pfvg=nfvg=pret_per=nret_per=0
pret=[]
nret=[]
for i in range(8,len(data)-8):
    bos=False
    break_liq=False
    if (data['low'][i+1]-data['high'][i-1])/data['close'][i]>0.0005:
        high=0
        j=2
        for j in range(2,8):
            if data['high'][i-j]>high:
                high=data['high'][i-j]
        if high<data['low'][i+1]:
            bos=True
        recent_high,recent_low=find_recent_swing_range(data[i-50:i-j])
        if recent_low is None:
            continue 
        for k in range(j,j+10):
            if data['low'][i-k]<recent_low:
                break_liq=True  
        if bos and break_liq:
            pfvg_ret+=data['close'][i+16]-data['close'][i]
            pfvg+=1
            pret_per+=(data['close'][i+16]-data['close'][i])/data['close'][i]
            pret.append(data['close'][i+16]-data['close'][i])
    elif (data['low'][i-1]-data['high'][i+1])/data['close'][i]>0.0005:
        bos=False
        break_liq=False 
        low=1e20
        j=2
        for j in range(2,8):
            if data['low'][i-j]<low:
                low=data['low'][i-j]
        if low>data['high'][i+1]:
            bos=True 
        recent_high,recent_low=find_recent_swing_range(data[i-50:i-j])
        if recent_high is None:
            continue
        for k in range(j,j+10):
            if recent_high<data['high'][i-k]:
                break_liq=True
        if bos and break_liq:
            nfvg_ret+=data['close'][i]-data['close'][i+16]
            nfvg+=1
            nret_per+=(data['close'][i]-data['close'][i+16])/data['close'][i]
            nret.append(data['close'][i]-data['close'][i+16])

In [436]:
pfvg_ret/pfvg,nfvg_ret/nfvg,pfvg,nfvg

(48.18353568166142, 183.11486970063504, 638, 630)

In [437]:
len(pret)

638

In [439]:
sum(1 for x in pret if x<0)

305

In [ ]:
def unmitigated(data):
    for i in range(8,len(data)-8):
        if data['low'][i+1]-data['high'][i-1]>25:
            mitigated=False 
            for j in range(i+2,i+8):
                if data['close'][j]<data['low'][i+1]:
                    mitigated=True
                    break
            if mitigated:
                return "pos"
        elif data['low'][i-1]-data['high'][i+1]>25:
            mitigated=False
            for j in range(i+2,i+8):
                if data['close'][j]>data['high'][i+1]:
                    mitigated=True
                    break
            if mitigated:
                return "neg"
    return "none"

In [ ]:
def reaction(data):
    for i in range(8,len(data)-8):
        if data['low'][i+1]-data['high'][i-1]>25:
            reaction=True  
            for j in range(i+2,i+8):
                if data['close'][j]<data['high'][i-1]:
                    reaction=False
            if reaction:
                return "pos"
        elif data['low'][i-1]-data['high'][i+1]>25:
            reaction=True 
            for j in range(i+2,i+8):
                if data['close'][j]>data['low'][i-1]:
                    reaction=False
            if reaction:
                return "neg"
    return "none"

In [ ]:
def sup_res(data):
    for i in range(7,len(data)-7):
        if data['low'][i+1]-data['high'][i-1]>25:
            support=False
            for j in range(2,5):
                if data['high'][i-1]<data['high'][i-j]<data['low'][i+1]:
                    support=True
                if data['high'][i-j]>data['low'][i+1]:
                    support=False
                    break
            if support:
                return "pos"
        elif data['low'][i-1]-data['high'][i+1]>25:
            resistance=False
            for j in range(2,7):
                if data['high'][i+1]<data['low'][i-j]<data['low'][i-1]:
                    resistance=True 
                if data['low'][i-j]<data['high'][i+1]:
                    resistance=False
                    break
            if resistance:
                return "neg"
    return "none"

In [ ]:
unmitigated(data[100:6000].reset_index(drop=True))

'neg'

In [ ]:
count=0
none=0
i=20
while i<len(data)-20:
    u=unmitigated(data[i:i+20].reset_index(drop=True))
    r=reaction(data[i:i+20].reset_index(drop=True))
    sr=sup_res(data[i:i+20].reset_index(drop=True))
    if u=="pos" or u=="neg":
        count+=1
    if r=="pos" or r=="neg":
        count+=1
    if sr=="pos" or sr=="neg":
        count+=1
    if u=="none":
        none+=1 
    if r=="none":
        none+=1 
    if sr=="none":
        none+=1  
    i+=20

In [269]:
count,none

(3650, 7880)